adding whalepass
moonbeam-foundation/app-directory-data pull request #37
Opened 2024-05-09 22:20 UTC by hshar7

2024-05-09 22:30 UTC, themacexpert commented
@hshar7 The Discord Link is expired. Everything else looks good!

2024-05-09 22:30 UTC, themacexpert requested changes
discord link

2024-05-09 23:16 UTC, hshar7 commented
@themacexpert that link seems to be working for me. But I've added an alternative one

2024-07-24 18:13 UTC, themacexpert approved these changes
LGTM 👍

2024-07-24 18:14 UTC, merged