add polybots
moonbeam-foundation/app-directory-data pull request #66
Opened 2024-10-01 13:06 UTC by ffatique

Add our game Polybots Rumble

2024-10-01 13:19 UTC, Rihyx requested changes
Please update the crate date.

2024-10-01 13:19 UTC, Rihyx commented on projects/polybots/polybots.json
> +  "projectCreationDate": 1710776529
```suggestion
  "projectCreationDate": 1710776529000
```

2024-10-01 16:15 UTC, ffatique commented on projects/polybots/polybots.json
> +    "twitter": "https://polybotsgame.io/",
Sorry, this is the correct link https://twitter.com/polybotsrumble, I will fix it

2024-10-01 16:47 UTC, themacexpert approved these changes

2024-10-02 07:44 UTC, Rihyx approved these changes

2024-10-02 07:44 UTC, merged